### PR TITLE
Save progress: 20.1

### PR DESCRIPTION
**Pull request by gitfoot**

### CODE REVIEW

**Comment by gitfoot** [comment]
Still don't know how does the integration between freecodecamp and github properly works

**Comment by gikf** [comment]
Hey @ElBigfoot

Looks like this PR was supposed to be made on your own fork, instead of the original boilerplate repository.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by gitfoot** [comment]
Thank you for the clarification, How does this thing with the FreecodeCamp
works??

Is there any tutorial?

Best

Oscar

**Comment by gikf** [comment]
I'm not sure which thing you mean exactly... either way, more convenient for such questions will be  [our chat room](https://chat.freecodecamp.org) or [the forum](https://forum.freecodecamp.org/).

**Pull request closed without merging**
